server:
  port: 8040
spring:
  application:
    name: shop-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.56.112.40:8848
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他微服务
          enabled: true
      routes:
#       - id: user-centre-add-bonus
#         uri: lb://user-centre
#         predicates:
#           - TimeBetween=上午10:00,下午3:00
#         filters:
#           - PreLog=a,b
        - id: user_route
          uri: lb://user-center
          predicates:
            - Path=/users/**
        - id: content_route
          uri: lb://content-center
          predicates:
            - Path=/shares/**,/admin/**
############################################################
#
# 日志
#
###########################################################
logging:
  level:
    com.alibaba.nacos: error
    org.springframework.cloud.gateway: trace
############################################################
#
# 配置端点信息
#
###########################################################
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

