server:
  port: 8040
spring:
  application:
    name: shop-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.56.112.40:8848
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他微服务
          enabled: true
      routes:
        - id: user-centre-add-bonus
          url: lb://user-center
          predicates
############################################################
#
# 配置端点信息
#
###########################################################
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
