############################################################
#
# web访问端口配置 约定：8088
#
############################################################
server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
############################################################
#
# 配置数据源信息
#
############################################################
spring:
  application:
    name: contain-centre
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource            # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver            # mysql驱动
    url: jdbc:mysql://106.12.137.47:3306/content_center?useUnicode=true&characterEncoding=UTF-8&autoReconnect&useSSL=false
    username: root
    password: lyp19891117
    hikari:
      connection-timeout: 30000  # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5                    # 最小连接数
      maximum-pool-size: 20              # 最大连接数
      auto-commit: true                  # 自动提交
      idle-timeout: 600000               # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP      # 连接池名字
      max-lifetime: 1800000              # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1
  ############################################################
  #
  # 配置nacos服务配置中心
  #
  ############################################################
  cloud:
    nacos:
      discovery:
        server-addr: 47.56.112.40:8848         # 指定nacos server的地址
    sentinel:
      filter:
      # 打开/关闭掉对Spring MVC端点的保护 false 为关闭 true 为打开
        enabled: false
      transport:
        dashboard: localhost:9000           #指定控制台地址
        client-ip: 127.0.0.1                #指定和控制台通信IP
        port: 9999                          #指定和控制台通信端口,默认值8719,如果不设置,会自动从8719开始扫描,依次+1,直到找到未被占用的端口
        heartbeat-interval-ms: 10000        #心跳发送周期,默认值null, 但在SimpleHttpHeartbeatSender会默认值10秒
      eager: true                           # 禁用懒加载
# 这里注意如果启动类中加了扫包注解@MapperScan， 这里可不要下面这个配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.contain.centre.entity  # 别名

logging:
  level:
    com.contain.centre.feignclient.UserCentreFeignClient: info
    com.contain.centre.mapper: debug
############################################################
#
# feign日志打印
#
############################################################
feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 指定单个服务名称-> user-centre   全局配置feign日志-> default
      default:
        # full 全部级别生产时禁止使用(feign性能优化)
        loggerLevel: full
  httpclient:
     # 让feign使用apache httpclient做请求；而不是默认的urlC onnection
     enabled: true
     # feign的最大连接数
     max-connections: 200
     # feign单个路径的最大连接数
     max-connections-per-route: 50
############################################################
#
# rocket-mq配置
#
############################################################
rocketmq:
    name-server: 47.56.112.40:9876
    producer:
      #必须指定group
      group: user-info-group
############################################################
#
# 监控所有端点
#
############################################################
management:
  endpoints:
    web:
      exposure:
        include: '*'




